version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/inss-discount-app
      - bundler_gems:/user/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"  # Porta padrão do Redis

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Porta para a interface web do Mailcatcher
      - "1025:1025"  # Porta SMTP para recebimento de e-mails
    container_name: mailcatcher
volumes: 
    postgres:
    bundler_gems: