name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: inss_test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: my-app:${{ github.sha }}
          cache-from: type=registry,ref=my-app:cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Create tmp/db directory and set permissions
        run: |
          mkdir -p ./tmp/db
          sudo chmod -R 777 ./tmp/db

      - name: Start Docker Compose services
        run: docker-compose up -d db

      - name: Wait for PostgreSQL to be ready
        run: |
          docker-compose exec -T db sh -c 'until pg_isready -U postgres; do sleep 1; done'

      - name: Run tests
        run: docker-compose run --rm web rake test
