name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10
        ports:
          - 3000:3000
        options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: docker/cache-action@v2
      with:
        path: |
          /tmp/docker
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Build Docker image
      run: docker build -t inss-discount-app .

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for database to be ready
      run: |
        while ! docker-compose exec -T db pg_isready -U postgres; do
          sleep 1
        done

    - name: Run database migrations
      run: docker-compose run web bundle exec rake db:migrate

    - name: Run tests
      run: docker-compose run web bundle exec rspec

    - name: Shut down Docker Compose
      run: docker-compose down
